# Generated by Django 3.2.8 on 2021-10-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_store',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
